In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentances 
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## define the vocabulary size
voc_size  =10000 

In [5]:
### One hot representation for every word

one_hot_repr = [one_hot(words,voc_size) for words in sent]

In [6]:
one_hot_repr

[[6743, 151, 6564, 1184],
 [6743, 151, 6564, 9732],
 [6743, 5253, 6564, 5172],
 [6215, 6378, 4045, 4503, 1072],
 [6215, 6378, 4045, 4503, 9093],
 [1353, 6743, 4669, 6564, 7411],
 [7813, 3637, 4877, 4503]]

In [21]:
## word embedding representation

from tensorflow.keras.layers import Embedding,Input 
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
## all the sentences dont have same length, to make them same length we have to use pad_sequences 
## this adds zeros in front/backs , pre for front , post for last
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
embedded_docs


array([[   0,    0,    0,    0, 6743,  151, 6564, 1184],
       [   0,    0,    0,    0, 6743,  151, 6564, 9732],
       [   0,    0,    0,    0, 6743, 5253, 6564, 5172],
       [   0,    0,    0, 6215, 6378, 4045, 4503, 1072],
       [   0,    0,    0, 6215, 6378, 4045, 4503, 9093],
       [   0,    0,    0, 1353, 6743, 4669, 6564, 7411],
       [   0,    0,    0,    0, 7813, 3637, 4877, 4503]], dtype=int32)

In [10]:
## feature representation 
dim = 10 


In [24]:
model = Sequential()

model.add(Input(shape=(sent_length,)))
model.add(Embedding(input_dim=voc_size,output_dim=dim))
model.compile('adam','mse')

In [25]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step


array([[[ 0.04500166, -0.01611478,  0.00301677, -0.03950274,
         -0.04434678,  0.01281072,  0.00646062, -0.0484512 ,
          0.03620834,  0.03396894],
        [ 0.04500166, -0.01611478,  0.00301677, -0.03950274,
         -0.04434678,  0.01281072,  0.00646062, -0.0484512 ,
          0.03620834,  0.03396894],
        [ 0.04500166, -0.01611478,  0.00301677, -0.03950274,
         -0.04434678,  0.01281072,  0.00646062, -0.0484512 ,
          0.03620834,  0.03396894],
        [ 0.04500166, -0.01611478,  0.00301677, -0.03950274,
         -0.04434678,  0.01281072,  0.00646062, -0.0484512 ,
          0.03620834,  0.03396894],
        [-0.02211604, -0.02826501,  0.03421236, -0.04034692,
         -0.04442347, -0.01169679, -0.02408905,  0.03394466,
         -0.00618962, -0.04515023],
        [ 0.01545786, -0.04014437, -0.0329717 , -0.03336616,
         -0.00698757,  0.02688456,  0.02037271, -0.00240038,
          0.04690615, -0.01450608],
        [-0.04899503, -0.01890313, -0.03177058, -0.0

In [28]:
embedded_docs[0]

array([   0,    0,    0,    0, 6743,  151, 6564, 1184], dtype=int32)

In [30]:
embedded_docs_0 = np.array([embedded_docs[0]])

In [31]:
model.predict(embedded_docs_0)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


array([[[ 0.04500166, -0.01611478,  0.00301677, -0.03950274,
         -0.04434678,  0.01281072,  0.00646062, -0.0484512 ,
          0.03620834,  0.03396894],
        [ 0.04500166, -0.01611478,  0.00301677, -0.03950274,
         -0.04434678,  0.01281072,  0.00646062, -0.0484512 ,
          0.03620834,  0.03396894],
        [ 0.04500166, -0.01611478,  0.00301677, -0.03950274,
         -0.04434678,  0.01281072,  0.00646062, -0.0484512 ,
          0.03620834,  0.03396894],
        [ 0.04500166, -0.01611478,  0.00301677, -0.03950274,
         -0.04434678,  0.01281072,  0.00646062, -0.0484512 ,
          0.03620834,  0.03396894],
        [-0.02211604, -0.02826501,  0.03421236, -0.04034692,
         -0.04442347, -0.01169679, -0.02408905,  0.03394466,
         -0.00618962, -0.04515023],
        [ 0.01545786, -0.04014437, -0.0329717 , -0.03336616,
         -0.00698757,  0.02688456,  0.02037271, -0.00240038,
          0.04690615, -0.01450608],
        [-0.04899503, -0.01890313, -0.03177058, -0.0